# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/hit-consistency

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/hit-consistency

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/hit-consistency/CMakeFiles /root/hit-consistency//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/hit-consistency/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raft_client

# Build rule for target.
raft_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raft_client
.PHONY : raft_client

# fast build rule for target.
raft_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/build
.PHONY : raft_client/fast

#=============================================================================
# Target rules for targets named raft_server

# Build rule for target.
raft_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raft_server
.PHONY : raft_server

# fast build rule for target.
raft_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/build
.PHONY : raft_server/fast

cpp/node.o: cpp/node.cc.o
.PHONY : cpp/node.o

# target to build an object file
cpp/node.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/node.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/node.cc.o
.PHONY : cpp/node.cc.o

cpp/node.i: cpp/node.cc.i
.PHONY : cpp/node.i

# target to preprocess a source file
cpp/node.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/node.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/node.cc.i
.PHONY : cpp/node.cc.i

cpp/node.s: cpp/node.cc.s
.PHONY : cpp/node.s

# target to generate assembly for a file
cpp/node.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/node.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/node.cc.s
.PHONY : cpp/node.cc.s

cpp/raft_service.o: cpp/raft_service.cc.o
.PHONY : cpp/raft_service.o

# target to build an object file
cpp/raft_service.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/raft_service.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/raft_service.cc.o
.PHONY : cpp/raft_service.cc.o

cpp/raft_service.i: cpp/raft_service.cc.i
.PHONY : cpp/raft_service.i

# target to preprocess a source file
cpp/raft_service.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/raft_service.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/raft_service.cc.i
.PHONY : cpp/raft_service.cc.i

cpp/raft_service.s: cpp/raft_service.cc.s
.PHONY : cpp/raft_service.s

# target to generate assembly for a file
cpp/raft_service.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/raft_service.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/raft_service.cc.s
.PHONY : cpp/raft_service.cc.s

cpp/repeated_timer_task.o: cpp/repeated_timer_task.cc.o
.PHONY : cpp/repeated_timer_task.o

# target to build an object file
cpp/repeated_timer_task.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/repeated_timer_task.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/repeated_timer_task.cc.o
.PHONY : cpp/repeated_timer_task.cc.o

cpp/repeated_timer_task.i: cpp/repeated_timer_task.cc.i
.PHONY : cpp/repeated_timer_task.i

# target to preprocess a source file
cpp/repeated_timer_task.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/repeated_timer_task.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/repeated_timer_task.cc.i
.PHONY : cpp/repeated_timer_task.cc.i

cpp/repeated_timer_task.s: cpp/repeated_timer_task.cc.s
.PHONY : cpp/repeated_timer_task.s

# target to generate assembly for a file
cpp/repeated_timer_task.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/repeated_timer_task.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/repeated_timer_task.cc.s
.PHONY : cpp/repeated_timer_task.cc.s

cpp/replicator.o: cpp/replicator.cc.o
.PHONY : cpp/replicator.o

# target to build an object file
cpp/replicator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/replicator.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/replicator.cc.o
.PHONY : cpp/replicator.cc.o

cpp/replicator.i: cpp/replicator.cc.i
.PHONY : cpp/replicator.i

# target to preprocess a source file
cpp/replicator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/replicator.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/replicator.cc.i
.PHONY : cpp/replicator.cc.i

cpp/replicator.s: cpp/replicator.cc.s
.PHONY : cpp/replicator.s

# target to generate assembly for a file
cpp/replicator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/cpp/replicator.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/cpp/replicator.cc.s
.PHONY : cpp/replicator.cc.s

examples/raft_client.o: examples/raft_client.cc.o
.PHONY : examples/raft_client.o

# target to build an object file
examples/raft_client.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/examples/raft_client.cc.o
.PHONY : examples/raft_client.cc.o

examples/raft_client.i: examples/raft_client.cc.i
.PHONY : examples/raft_client.i

# target to preprocess a source file
examples/raft_client.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/examples/raft_client.cc.i
.PHONY : examples/raft_client.cc.i

examples/raft_client.s: examples/raft_client.cc.s
.PHONY : examples/raft_client.s

# target to generate assembly for a file
examples/raft_client.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/examples/raft_client.cc.s
.PHONY : examples/raft_client.cc.s

examples/raft_server.o: examples/raft_server.cc.o
.PHONY : examples/raft_server.o

# target to build an object file
examples/raft_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/examples/raft_server.cc.o
.PHONY : examples/raft_server.cc.o

examples/raft_server.i: examples/raft_server.cc.i
.PHONY : examples/raft_server.i

# target to preprocess a source file
examples/raft_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/examples/raft_server.cc.i
.PHONY : examples/raft_server.cc.i

examples/raft_server.s: examples/raft_server.cc.s
.PHONY : examples/raft_server.s

# target to generate assembly for a file
examples/raft_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/examples/raft_server.cc.s
.PHONY : examples/raft_server.cc.s

raft_message.pb.o: raft_message.pb.cc.o
.PHONY : raft_message.pb.o

# target to build an object file
raft_message.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/raft_message.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/raft_message.pb.cc.o
.PHONY : raft_message.pb.cc.o

raft_message.pb.i: raft_message.pb.cc.i
.PHONY : raft_message.pb.i

# target to preprocess a source file
raft_message.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/raft_message.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/raft_message.pb.cc.i
.PHONY : raft_message.pb.cc.i

raft_message.pb.s: raft_message.pb.cc.s
.PHONY : raft_message.pb.s

# target to generate assembly for a file
raft_message.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_client.dir/build.make CMakeFiles/raft_client.dir/raft_message.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raft_server.dir/build.make CMakeFiles/raft_server.dir/raft_message.pb.cc.s
.PHONY : raft_message.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raft_client"
	@echo "... raft_server"
	@echo "... cpp/node.o"
	@echo "... cpp/node.i"
	@echo "... cpp/node.s"
	@echo "... cpp/raft_service.o"
	@echo "... cpp/raft_service.i"
	@echo "... cpp/raft_service.s"
	@echo "... cpp/repeated_timer_task.o"
	@echo "... cpp/repeated_timer_task.i"
	@echo "... cpp/repeated_timer_task.s"
	@echo "... cpp/replicator.o"
	@echo "... cpp/replicator.i"
	@echo "... cpp/replicator.s"
	@echo "... examples/raft_client.o"
	@echo "... examples/raft_client.i"
	@echo "... examples/raft_client.s"
	@echo "... examples/raft_server.o"
	@echo "... examples/raft_server.i"
	@echo "... examples/raft_server.s"
	@echo "... raft_message.pb.o"
	@echo "... raft_message.pb.i"
	@echo "... raft_message.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

